version: '3.4'

services:
  ordermicroservice.api:
    image: ordermicroserviceapi
    build:
      context: .
      dockerfile: OrderMicroservice.Api/Dockerfile
    environment:
     - MONGODB_HOST=mongodb-container
     - MONGODB_PORT=27017
     - MONGODB_DATABASE=OrdersDatabase
     - UsersMicroserviceName=users-microservice
     - UsersMicroservicePort=8080
     - ProductsMicroserviceName=products-microservice
     - ProductsMicroservicePort=8080
     - REDIS_HOST=redis
     - REDIS_PORT=6379
    ports:
     - "7000:8080"
    networks:
     - orders-mongodb-network
     - ecommerce-network
    depends_on:
     - mongodb-container

  mongodb-container:
   image: mongo:latest
   ports:
    - "27017:27017"
   volumes:
    - ../mongodb-init:/docker-entrypoint-initdb.d
   networks:
    - orders-mongodb-network


  users-microservice:
   image: users-microservice:latest
   environment:
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_HTTP_ENVIRONMENT=Development
    - POSTGRES_HOST=postgres-container
    - POSTGRES_PORT=5432
    - POSTGRES_DATABASE=eMicroUsers
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=7882
   ports:
    - "5000:8080"
   networks:
    - users-postgres-network
    - ecommerce-network
   depends_on:
    - postgres-container


  postgres-container:
   image: postgres:13
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=7882
    - POSTGRES_DB=eMicroUsers
   ports:
    - "5434:5432"
   volumes:
    - ../postgres-init:/docker-entrypoint-initdb.d
   networks:
    - users-postgres-network


  products-microservice:
   image: products-microservice:latest
   environment:
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_ENVIRONMENT=Development
    - MYSQL_HOST=mysql-container
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=ecommerceproductsdatabase
    - MYSQL_USER=root
    - MYSQL_PASSWORD=7882
   ports:
    - "6000:8080"
   networks:
    - products-mysql-network
    - ecommerce-network
   depends_on:
    - mysql-container
  

  mysql-container:
   image: mysql:8.0
   environment:
    - MYSQL_ROOT_PASSWORD=7882
   ports:
    - "3307:3306"
   volumes:
    - ../mysql-init:/docker-entrypoint-initdb.d
   networks:
    - products-mysql-network
  

  redis:
   image: redis:latest
   ports:
    - "6379:6379"
   volumes:
    - ../redis-cache:/data
   networks:
    - ecommerce-network
  

networks:
 orders-mongodb-network:
  driver: bridge
 products-mysql-network:
  driver: bridge
 users-postgres-network:
  driver: bridge
 ecommerce-network:
  driver: bridge